version: '3.8'

services:
  gamma:
    container_name: 'gamma-mon'
    image: 'ghcr.io/lnls-sirius/gamma-mon:1.0.2'
    build:
      context: .
    ports:
      - 80:80

  gamma-latest:
    container_name: 'gamma-mon'
    image: 'ghcr.io/lnls-sirius/gamma-mon'
    build:
      context: .
    ports:
      - 80:80
